---
abstract: 'UAV::Pilot driver for the WumpusRover'
author:
  - 'Timm Murray <tmurray@wumpus-cave.net>'
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UAV-Pilot-WumpusRover
provides:
  UAV::Pilot::WumpusRover:
    file: lib/UAV/Pilot/WumpusRover.pm
    version: 0.1
  UAV::Pilot::WumpusRover::Control:
    file: lib/UAV/Pilot/WumpusRover/Control.pm
    version: 0
  UAV::Pilot::WumpusRover::Control::Event:
    file: lib/UAV/Pilot/WumpusRover/Control/Event.pm
    version: 0
  UAV::Pilot::WumpusRover::Driver:
    file: lib/UAV/Pilot/WumpusRover/Driver.pm
    version: 0
  UAV::Pilot::WumpusRover::Driver::Mock:
    file: lib/UAV/Pilot/WumpusRover/Driver/Mock.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet:
    file: lib/UAV/Pilot/WumpusRover/Packet.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet::Ack:
    file: lib/UAV/Pilot/WumpusRover/Packet/Ack.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet::Heartbeat:
    file: lib/UAV/Pilot/WumpusRover/Packet/Heartbeat.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet::RadioMaxes:
    file: lib/UAV/Pilot/WumpusRover/Packet/RadioMaxes.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet::RadioMins:
    file: lib/UAV/Pilot/WumpusRover/Packet/RadioMins.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet::RadioOutputs:
    file: lib/UAV/Pilot/WumpusRover/Packet/RadioOutputs.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet::RadioTrims:
    file: lib/UAV/Pilot/WumpusRover/Packet/RadioTrims.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet::RequestStartupMessage:
    file: lib/UAV/Pilot/WumpusRover/Packet/RequestStartupMessage.pm
    version: 0
  UAV::Pilot::WumpusRover::Packet::StartupMessage:
    file: lib/UAV/Pilot/WumpusRover/Packet/StartupMessage.pm
    version: 0
  UAV::Pilot::WumpusRover::PacketFactory:
    file: lib/UAV/Pilot/WumpusRover/PacketFactory.pm
    version: 0
  UAV::Pilot::WumpusRover::Video:
    file: lib/UAV/Pilot/WumpusRover/Video.pm
    version: 0
  UAV::Pilot::WumpusRover::Video::Mock:
    file: lib/UAV/Pilot/WumpusRover/Video/Mock.pm
    version: 0
recommends:
  Getopt::Long: 0
  UAV::Pilot::SDL: 0
  UAV::Pilot::Video::Ffmpeg: 0
requires:
  AnyEvent: 0
  Digest::Adler32::XS: 0
  File::ShareDir: 1.00
  Moose: 0
  MooseX::Event: 0
  Test::More: 0
  Tie::IxHash: 0
  UAV::Pilot: 0.9
  namespace::autoclean: 0
  perl: v5.14.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://github.com/frezik/UAV-Pilot-WumpusRover
version: 0.1
